# Basic Python

## 1. Split this string

In [6]:
s = "Hi there Sam!"

In [7]:
string=s.split()
print(string)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [8]:
planet = "Earth"
diameter = 12742

In [9]:
p="The diameter of {} is {} Kilometers"
p.format(planet,diameter)

'The diameter of Earth is 12742 Kilometers'

## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
p=np.zeros(10)
print(p)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
a=np.ones(10)*5
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [17]:
e=np.arange(20,35,2)
print(e)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
m=np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b),axis=None))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [20]:
import pandas as pd


In [21]:
data={'Name':['Swetha','Divya','Maran'], 'Marks':[94,98,99]}
d=pd.DataFrame(data,index=[1,2,3])
print(d)

     Name  Marks
1  Swetha     94
2   Divya     98
3   Maran     99


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
d=pd.date_range(start='01-01-2023',end='10-02-2023')
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
d=pd.DataFrame(lists,columns=['S.No','Name','Roll No'])
print(d)

   S.No Name  Roll No
0     1  aaa       22
1     2  bbb       25
2     3  ccc       24
